# Generated by Django 2.0.1 on 2018-01-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='too',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first', models.TextField()),
                ('second', models.TextField()),
                ('third', models.TextField()),
            ],
        ),
    ]
