# Generated by Django 2.0.1 on 2018-01-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_too'),
    ]

    operations = [
        migrations.RenameField(
            model_name='too',
            old_name='third',
            new_name='name',
        ),
    ]
