# Generated by Django 2.0.1 on 2018-01-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180107_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
            ],
        ),
    ]
