# Generated by Django 2.0.1 on 2018-01-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
