# Generated by Django 2.0.1 on 2018-01-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_quest_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='option1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='option2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='option3',
            field=models.TextField(null=True),
        ),
    ]
