# Generated by Django 2.0.1 on 2018-01-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180112_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='too',
            name='resO',
            field=models.IntegerField(null=True),
        ),
    ]
