# Generated by Django 2.0.1 on 2018-01-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_too_reso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='too',
            name='first',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='too',
            name='second',
            field=models.IntegerField(),
        ),
    ]
