# Generated by Django 2.0.1 on 2018-01-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180112_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='too',
            name='first',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='too',
            name='second',
            field=models.IntegerField(null=True),
        ),
    ]
